import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../_styles/animation.css';
import "./globals.css";
import "react-day-picker/dist/style.css";
import Header from "@/_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Myxellia homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
